// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQS2JOR8nJWLCHaRG6HD-I9mvAC5eh_w',
    appId: '1:795000728222:web:4af843616098babb57a98f',
    messagingSenderId: '795000728222',
    projectId: 'politics-app-1234',
    authDomain: 'politics-app-1234.firebaseapp.com',
    storageBucket: 'politics-app-1234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDThOAs9CdnDg_puLLPX2L1V_QMKzR5_Cg',
    appId: '1:795000728222:android:3c7de1e582e165d457a98f',
    messagingSenderId: '795000728222',
    projectId: 'politics-app-1234',
    storageBucket: 'politics-app-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqaQ3GYD4Qxg3bcUK2QBzsvYvEy1gfMV0',
    appId: '1:795000728222:ios:a135c0a8df77933057a98f',
    messagingSenderId: '795000728222',
    projectId: 'politics-app-1234',
    storageBucket: 'politics-app-1234.firebasestorage.app',
    iosBundleId: 'com.example.politicsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqaQ3GYD4Qxg3bcUK2QBzsvYvEy1gfMV0',
    appId: '1:795000728222:ios:a135c0a8df77933057a98f',
    messagingSenderId: '795000728222',
    projectId: 'politics-app-1234',
    storageBucket: 'politics-app-1234.firebasestorage.app',
    iosBundleId: 'com.example.politicsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQS2JOR8nJWLCHaRG6HD-I9mvAC5eh_w',
    appId: '1:795000728222:web:8b24b4a04cb2b4e057a98f',
    messagingSenderId: '795000728222',
    projectId: 'politics-app-1234',
    authDomain: 'politics-app-1234.firebaseapp.com',
    storageBucket: 'politics-app-1234.firebasestorage.app',
  );
}
